spring:
  application:
    name: voltpay-writer
  liquibase:
    default-schema: write
  datasource:
    url: jdbc:postgresql://localhost:5432/write_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 10
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094,localhost:9095,localhost:9096
    consumer:
      group-id: writer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      max-poll-records: 500
      fetch-max-wait: 500
      fetch-min-size: 1
      enable-auto-commit: false
    listener:
      type: batch
      ack-mode: MANUAL_IMMEDIATE
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer