spring:
  application:
    name: voltpay-writer
  liquibase:
    default-schema: write
  datasource:
    url: jdbc:postgresql://localhost:5432/write_db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: HikariCP
      maximum-pool-size: 50
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093
    properties:
      client:
        dns:
          lookup: use_all_dns_ips
    consumer:
      group-id: writer-group
      max-poll-records: 500
      fetch-max-wait: 500
      fetch-min-size: 1
      enable-auto-commit: false
    listener:
      type: batch

kafka:
  dlt:
    enabled: false