CREATE SCHEMA IF NOT EXISTS write;

CREATE TABLE IF NOT EXISTS write.payment_core (
 id VARCHAR(26) PRIMARY KEY,
 amount NUMERIC(20, 6),
 status INTEGER,
 CURRENCY VARCHAR(3),
 CUST_ID BIGINT,
 TYPE VARCHAR(3),
 CREATED_AT TIMESTAMP
);

CREATE TABLE IF NOT EXISTS write.payment_metadata (
 id VARCHAR(26) not null,
 CREATED_AT TIMESTAMP,
 UPDATED_AT TIMESTAMP,
 VERSION INTEGER
);

CREATE TABLE IF NOT EXISTS write.payment_notes (
 id VARCHAR(26) NOT NULL,
 EXTERNAL_REF_ID VARCHAR(200) NOT NULL,
 COMMENT VARCHAR(300),
 CREATED_AT TIMESTAMP
);

